# Generated by Django 4.2.23 on 2025-07-06 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='데이터셋 이름')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('file', models.FileField(upload_to='data_files/', verbose_name='데이터 파일')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드 날짜')),
            ],
        ),
        migrations.CreateModel(
            name='DatasetConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='데이터셋 설정의 고유 이름 (예: WineQualityRed)', max_length=100, unique=True)),
                ('file_path', models.CharField(help_text='데이터셋 파일의 상대 경로 (예: winequality-red.csv)', max_length=255)),
                ('target_column', models.CharField(help_text='타겟 변수 컬럼 이름', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '데이터셋 설정',
                'verbose_name_plural': '데이터셋 설정',
            },
        ),
        migrations.CreateModel(
            name='FeatureConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='피처 설정의 고유 이름 (예: WineFeatures_All)', max_length=100, unique=True)),
                ('features', models.TextField(default='[]', help_text='학습에 사용할 피처 리스트 (JSON 배열 형식의 문자열)')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset_config', models.ForeignKey(help_text='이 피처 조합이 적용될 데이터셋', on_delete=django.db.models.deletion.CASCADE, related_name='feature_configs', to='mymlopsapp1.datasetconfig')),
            ],
            options={
                'verbose_name': '피처 설정',
                'verbose_name_plural': '피처 설정',
                'unique_together': {('name', 'dataset_config')},
            },
        ),
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='모델 이름')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('algorithm', models.CharField(max_length=100, verbose_name='알고리즘 (예: RandomForest, LogisticRegression)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 날짜')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='학습 파라미터')),
                ('accuracy', models.FloatField(blank=True, null=True, verbose_name='정확도')),
                ('precision', models.FloatField(blank=True, null=True, verbose_name='정밀도')),
                ('recall', models.FloatField(blank=True, null=True, verbose_name='재현율')),
                ('f1_score', models.FloatField(blank=True, null=True, verbose_name='F1 스코어')),
                ('training_duration_seconds', models.FloatField(blank=True, null=True, verbose_name='학습 시간 (초)')),
                ('model_file_path', models.CharField(blank=True, max_length=500, verbose_name='학습된 모델 파일 경로')),
                ('trained_at', models.DateTimeField(auto_now_add=True, verbose_name='학습 완료 시간')),
                ('version', models.CharField(blank=True, max_length=50, verbose_name='결과 버전')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_results', to='mymlopsapp1.dataset', verbose_name='사용된 데이터셋')),
                ('ml_model_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_results', to='mymlopsapp1.mlmodel', verbose_name='모델 설정')),
            ],
            options={
                'ordering': ['-trained_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='모델 설정의 고유 이름 (예: WineQuality_LogisticRegression)', max_length=100, unique=True)),
                ('model_type', models.CharField(help_text='사용할 모델 타입 (예: LogisticRegression, RandomForest)', max_length=50)),
                ('parameters', models.TextField(default='{}', help_text='모델 하이퍼파라미터 (JSON 객체 형식의 문자열)')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset_config', models.ForeignKey(help_text='이 모델이 사용할 데이터셋', on_delete=django.db.models.deletion.CASCADE, to='mymlopsapp1.datasetconfig')),
                ('feature_config', models.ForeignKey(help_text='이 모델이 사용할 피처 조합', on_delete=django.db.models.deletion.CASCADE, to='mymlopsapp1.featureconfig')),
            ],
            options={
                'verbose_name': '모델 설정',
                'verbose_name_plural': '모델 설정',
            },
        ),
    ]
