## environment.yml

name: mlops-env # Conda 환경 이름
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9 # 사용할 Python 버전
  - django=4.2 # Django 버전 (혹은 원하는 최신 안정 버전)
  - pandas
  - scikit-learn
  - jupyter # 데이터 탐색 및 스크립트 실행용 (선택 사항)
  - joblib # 모델 저장/로드용
  - numpy # 수치 계산
  - scipy # 과학 계산
  - matplotlib # 시각화
  - seaborn # 통계 시각화
  - pillow # 이미지 처리
  # - celery # 비동기 태스크를 위해 필요하다면 추가
  # - redis # Celery와 함께 사용 (메시지 브로커)

  # Pip 패키지 (Conda에 없는 패키지)
  - pip
  - pip:
    - djangorestframework # Django REST Framework (API 개발 시 필요)
    - django-filter # REST Framework 필터링용 (선택 사항)
    - psycopg2-binary
    - python-dotenv # 환경 변수 관리
    - pandas
    # - mlflow # MLflow를 사용한다면 추가
    # - dvc # DVC를 사용한다면 추가
